### ISSUE TITLE
Plugin seem cannot work

### ISSUE THREAD

**Issue by lnh089** [GEROMAX/redmine_subtask_list_accordion#11]
Hello,when I have install this plugin,and I have setup as below,but it seem have't any change,
![image](https://user-images.githubusercontent.com/21374477/33366504-6550fab0-d526-11e7-90d8-50720b7d2c1e.png)
![image](https://user-images.githubusercontent.com/21374477/33366555-8d6559e2-d526-11e7-916d-6e631d26c574.png)
![image](https://user-images.githubusercontent.com/21374477/33366570-9952166e-d526-11e7-8269-11a5731f6c51.png)
ask how so?Thank you!

**Comment by GEROMAX** [comment]
Hi @lnh089 .

You misunderstanding maybe.
This plugin work for 'Subtasks List' in a ticket, not tickets list.

Please see under the 'description' in a parent ticket.
