### ISSUE TITLE
Cannot expand first row

### ISSUE THREAD

**Issue by Coolllama** [GEROMAX/redmine_subtask_list_accordion#4]
Hi,

I don't know if I'm missing something (configuration and/or other plugins) but I cannot expand the first subtask using the arrow button (since there's no arrow button). Using "Expand/Collapse all" buttons works perfectly though. I think it considers that first row to be a "header row" as shown on the Redmine website (http://www.redmine.org/plugins/redmine_subtask_list_accordion). The problem is that I don't have that "header row" as you can see in the attached image below.

![image](https://cloud.githubusercontent.com/assets/27442785/26561048/278b5b86-4489-11e7-8d1d-087886ff91db.png)

Thanks for your help.

**Comment by GEROMAX** [comment]
Hi @Coolllama .

If you using plugin version with 1.3.0.
Could you try add this code at line 11 for  "_subtask_list_accordion_partial.html.erb".
May be resolution.
`$("table.list.issues > tbody > tr:first").before("<tr style='display:none;'></tr>");`

Please tell me.
Why without header row at your environment?

**Comment by Coolllama** [comment]
Hi there,

Thank you for your answer. I will try to add the line.

Regarding the header row, the only way to get one is to install this plugin 
http://www.redmine.org/plugins/subtask_list_columns

I didn't find any native Redmine configuration to activate a header row.

**Comment by GEROMAX** [comment]
Hi @Coolllama .
Thanks your answer.

By chance, I using same plugin. https://github.com/SMS-IT/redmine_subtask_list_columns
But not occur it in my environment.

You may have fail  'subtask_list_columns' plugin installation.
That is good plugin, but has some problems.

If you feel like it, you try my forked plugin.
https://github.com/GEROMAX/redmine_subtask_list_columns
It support Redmine version 3.3, and one bug fix.

**Comment by Coolllama** [comment]
Hi,

Thanks again for the answer. 

So that means we need to have the the subtask_list_column plugin in order to get a header line. As I said in my first comment, the only way I get a header is when I install the subtask_list_culumn plugin. Otherwise, the first row is considered as a normal subtask and cannot be expanded manually.

**Comment by Coolllama** [comment]
Hi again,

Regarding you forked subtask_list_column plugin, does it solve the problem that we cannot apply any changes from the subtask list project module if the language profile is not set to English? Only changes made in the plugin configuration (from administration menu) can be saved using a non-English language profile.

Kind regards,

**Comment by GEROMAX** [comment]
Hi there.

Oh.. I'm wrong guess. orz.
I thought Redmine had a header row by default. sorry.

This is fatal bug, but I'm busy now.
It will take about a month to release an official bug fix.

Did you solve the problem by add code line?
I try fix it as soon as possible.

And, the problem of 'subtask_list_columns' you have can not be resolved unfortunately by my forked plugin.
I'm using it too by trial and error in Japanese language.(There is no problem in practical use.)

The comment got longer, I appreciate your bug report.
Thanks.

**Comment by Coolllama** [comment]
Hello,

No problem, I can use the subtask_list_column plugin as a workaround for now.

Regarding the code line, it, unfortunately, does not solve the problem. I will look forward to your fix.

Thanks again for the support and, of course, for the plugin :)

Cheers,

**Comment by GEROMAX** [comment]
Hi @Coolllama .

Thank you for waiting.
I fixed this bug.

Support with/without header row on subtask-list now.
I could resolve at fast by @braini75 s PR.

Thanks @Coolllama and @braini75 !

**Comment by Coolllama** [comment]
Hi there,

Thanks to you guys. I will implement the fix.

Kind regard,

**Comment by GEROMAX** [comment]
Hi,

I close this issue.
If not yet resolved, report issue again.

Cheers,
