### ISSUE TITLE
subtask list has a bug

### ISSUE THREAD

**Issue by antoniodev200** [GEROMAX/redmine_subtask_list_accordion#8]
demo

1
  --> 2
  --> 3
4
  -->5
  -->6

like this ,the list is right

1
3
4
2
5
6

like this, the list is wrong

**Comment by GEROMAX** [comment]
Hi,

Is there a picture?
I want some more detailed information.

**Comment by GEROMAX** [comment]
Hi,

I use this plugin a long time. But I not found your reporting bug.
May be, Bugs are not caused by this plugin.

If you have problem, please report issue again.
